version: "3.7"
services: 
  app:
    build:
      dockerfile: dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./notes:/usr/src/app/notes
      - /var/run/docker.sock:/var/run/docker.sock